name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript type check
      run: npm run check

    - name: Build application
      run: npm run build

    - name: Run linting (if available)
      run: |
        if npm run lint --dry-run > /dev/null 2>&1; then
          npm run lint
        else
          echo "No lint script found, skipping linting"
        fi

    - name: Run tests (if available)
      run: |
        if npm run test --dry-run > /dev/null 2>&1; then
          npm run test
        else
          echo "No test script found, skipping tests"
        fi

    - name: Check for vulnerabilities
      run: |
        npm audit --audit-level=high || echo "Some vulnerabilities found, but continuing build"
        npm audit --audit-level=critical || true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          build/
        retention-days: 7
